# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 2
  end

  config.vm.define "runner" do |runner|
    runner.vm.network "forwarded_port", guest: 5000, host: 5000, auto_corrected: true, id: "registry"
    runner.vm.network "private_network", ip: "192.168.56.4"
    runner.vm.provision "file", source: "vars.yml", destination: "/vagrant/vars.yml"

    runner.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook_runner.yml"
    end
  end

  config.vm.define "appserver" do |appserver|
    appserver.vm.network "forwarded_port", guest: 8080, host: 8080, auto_corrected: true, id: "hello-spa"
    appserver.vm.network "private_network", ip: "192.168.56.5"
    appserver.vm.provision "file", source: "vars.yml", destination: "/vagrant/vars.yml"

    appserver.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook_appserver.yml"
    end
  end
end  
