name: hello-spa

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: hello-spa
        tags: v1, latest
        registry: registry.gr8cat.io:5000
        dockerfile: docker/Dockerfile
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: appleboy/ssh-action@master
      env:
        REG_USER: ${{ secrets.REGISTRY_USERNAME }}
        REG_PASS: ${{ secrets.REGISTRY_PASSWORD }}
      with:
        host: 192.168.56.5
        username: vagrant
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        envs: REG_USER,REG_PASS
        script: |
          echo $REG_PASS | docker login registry.gr8cat.io:5000 --username $REG_USER --password-stdin
          docker pull registry.gr8cat.io:5000/hello-spa
          docker container ls | grep -w "hello-spa"
          result=$?
          if [[ $result -eq 0 ]]; then
            docker stop hello-spa
            docker rm hello-spa
          fi
          docker run -d -p 8080:80 --name hello-spa registry.gr8cat.io:5000/hello-spa
