name: hello-spa Node.js

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  CHROME_BIN: /usr/bin/chromium-browser

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 13.12
        cache: 'npm'
    - run: npm install
    - run: npm run build
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: repo/image
        tags: v1, latest
        registry: hub.docker.com
        dockerfile: docker/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
  #test:
  #  runs-on: self-hosted
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: actions/setup-node@v3
  #    with:
  #      node-version: 13.12
  #      cache: 'npm'
  #  #- run: npm ci
  #  - run: npm install -g @angular/cli@9.1.0
  #  - run: npm install --save-dev @angular-devkit/build-angular
  #  - run: npm run test
    
  
