name: hello-spa

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  #build:
  #  runs-on: self-hosted
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: actions/setup-node@v3
  #    with:
  #      node-version: 13.12
  #      cache: 'npm'
  #  - run: npm install
  #  - run: npm run build
  
  docker-build:
    runs-on: self-hosted
    steps:
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: myrepo/hello-spa
        tags: v1, latest
        registry: docker.io
        dockerfile: docker/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  #test:
  #  runs-on: self-hosted
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: actions/setup-node@v3
  #    with:
  #      node-version: 16.16.0
  #      cache: 'npm'
  #  - run: npm install -g @angular/cli
  #  - run: npm install --save-dev @angular-devkit/build-angular
  #  - run: npm run test
