name: hello-spa

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  #build:
  #  runs-on: self-hosted
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: actions/setup-node@v3
  #    with:
  #      node-version: 13.12
  #      cache: 'npm'
  #  - run: npm install
  #  - run: npm run build
  testssh:
    runs-on: self-hosted
    steps:
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'vagrant@192.168.56.5'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: "echo ok"
  
  docker-build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: hello-spa
        #tags: v1, latest
        registry: localhost:5000
        dockerfile: docker/Dockerfile
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
        
        
  #test:
  #  runs-on: self-hosted
  #  steps:
  #  - uses: actions/checkout@v3
  #  - uses: actions/setup-node@v3
  #    with:
  #      node-version: 16.16.0
  #      cache: 'npm'
  #  - run: npm install -g @angular/cli
  #  - run: npm install --save-dev @angular-devkit/build-angular
  #  - run: npm run test
  
